--CREATE DATABASE
CREATE DATABASE RetailSalesDB;
GO

USE RetailSalesDB;
GO

--Create Table

CREATE TABLE retail_sales (
    transactions_id INT PRIMARY KEY,
    sale_date DATE,
    sale_time TIME,
    customer_id INT,
    gender VARCHAR(20),
    age INT,
    category VARCHAR(50),
    quantity INT,
    price_per_unit DECIMAL(10,2),
    cogs DECIMAL(10,2),
    total_sale DECIMAL(10,2)
);

--Import CSV into SSMS

BULK INSERT [RetailSalesDB].[dbo].[retail_sales]
FROM 'C:\Users\timmy\OneDrive\Desktop\SQL_Projects\Zero_Analyst\SQL_Retail_Sales_Analysis_.txt'
WITH (
    FIRSTROW = 2,              -- Skip header row
    FIELDTERMINATOR = ',',     -- CSV delimiter
    ROWTERMINATOR = '\n',      -- Line break
    TABLOCK
);

--Data Cleaning
--Check for NULL values

SELECT *
FROM retail_sales
WHERE transactions_id IS NULL
   OR sale_date IS NULL
   OR customer_id IS NULL
   OR total_sale IS NULL;


--Remove duplicate transactions

WITH duplicate_cte AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY transactions_id
               ORDER BY transactions_id
           ) AS row_num
    FROM retail_sales
)
DELETE FROM duplicate_cte
WHERE row_num > 1;


---Exploratory Data Analysis
--Total Number of Records

SELECT COUNT(*) AS total_records
FROM retail_sales;

--Total Revenue

SELECT SUM(total_sale) AS total_revenue
FROM retail_sales;


--Average Sale Value

SELECT AVG(total_sale) AS average_sale
FROM retail_sales;

--Distinct Product Categories

SELECT DISTINCT category
FROM retail_sales


----Business Analysis Queries
---Total Sales by Category

SELECT
    category,
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY category
ORDER BY total_sales DESC;


---Average Customer Age by Gender

SELECT
    gender,
    AVG(age) AS average_age
FROM retail_sales
GROUP BY gender;


---Monthly Revenue Trend

SELECT
    YEAR(sale_date) AS sales_year,
    MONTH(sale_date) AS sales_month,
    SUM(total_sale) AS monthly_revenue
FROM retail_sales
GROUP BY YEAR(sale_date), MONTH(sale_date)
ORDER BY sales_year, sales_month;


---Top 10 Customers by Spending

SELECT TOP 10
    customer_id,
    SUM(total_sale) AS total_spending
FROM retail_sales
GROUP BY customer_id
ORDER BY total_spending DESC;


---Best Selling Product Category

SELECT TOP 1
    category,
    SUM(quantity) AS total_quantity_sold
FROM retail_sales
GROUP BY category
ORDER BY total_quantity_sold DESC;


---Aggregate Function Queries
--Sales Statistics

SELECT
    MIN(total_sale) AS minimum_sale,
    MAX(total_sale) AS maximum_sale,
    AVG(total_sale) AS average_sale,
    SUM(total_sale) AS total_sales
FROM retail_sales;


--Revenue Generated by Gender

SELECT
    gender,
    SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY gender;


---Categories with Revenue Above 100000

SELECT
    category,
    SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY category
HAVING SUM(total_sale) > 100000;


---Subquery
--Customers Spending Above Average

SELECT customer_id,
       SUM(total_sale) AS customer_spending
FROM retail_sales
GROUP BY customer_id
HAVING SUM(total_sale) > (
    SELECT AVG(total_sale)
    FROM retail_sales
);


---Transactions Greater Than Overall Average Sale

SELECT *
FROM retail_sales
WHERE total_sale > (
    SELECT AVG(total_sale)
    FROM retail_sales
);


---Highest Sale in Each Category

SELECT *
FROM retail_sales rs
WHERE total_sale = (
    SELECT MAX(total_sale)
    FROM retail_sales
    WHERE category = rs.category
);


---CTE (Common Table Expression) Queries
--Monthly Sales Ranking

WITH monthly_sales AS (
    SELECT
        MONTH(sale_date) AS sales_month,
        SUM(total_sale) AS total_revenue
    FROM retail_sales
    GROUP BY MONTH(sale_date)
)
SELECT *,
       RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank
FROM monthly_sales;


---Customer Purchase Segmentation

WITH customer_totals AS (
    SELECT
        customer_id,
        SUM(total_sale) AS total_spent
    FROM retail_sales
    GROUP BY customer_id
)
SELECT
    customer_id,
    total_spent,
    CASE
        WHEN total_spent >= 10000 THEN 'High Value'
        WHEN total_spent >= 5000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer_totals;


--Running Total Sales

WITH daily_sales AS (
    SELECT
        sale_date,
        SUM(total_sale) AS daily_total
    FROM retail_sales
    GROUP BY sale_date
)
SELECT
    sale_date,
    daily_total,
    SUM(daily_total) OVER (
        ORDER BY sale_date
    ) AS running_total
FROM daily_sales;


---Temp Table Queries
--Store High Revenue Customers in Temp Table

CREATE TABLE #high_value_customers (
    customer_id INT,
    total_spending DECIMAL(10,2)
);

INSERT INTO #high_value_customers
SELECT
    customer_id,
    SUM(total_sale)
FROM retail_sales
GROUP BY customer_id
HAVING SUM(total_sale) > 5000;

SELECT *
FROM #high_value_customers;


---Temporary Sales Summary Table

SELECT
    category,
    SUM(total_sale) AS total_revenue,
    AVG(total_sale) AS avg_revenue
INTO #sales_summary
FROM retail_sales
GROUP BY category;

SELECT *
FROM #sales_summary;


---Window Function Queries
--Rank Customers by Spending

SELECT
    customer_id,
    SUM(total_sale) AS total_spending,
    RANK() OVER (
        ORDER BY SUM(total_sale) DESC
    ) AS customer_rank
FROM retail_sales
GROUP BY customer_id;


---Compare Current Sale with Previous Sale

SELECT
    transactions_id,
    sale_date,
    total_sale,
    LAG(total_sale) OVER (
        ORDER BY sale_date
    ) AS previous_sale
FROM retail_sales;


---Advanced Business Insights
--Peak Sales Hours

SELECT
    DATEPART(HOUR, sale_time) AS sales_hour,
    COUNT(*) AS total_transactions,
    SUM(total_sale) AS revenue
FROM retail_sales
GROUP BY DATEPART(HOUR, sale_time)
ORDER BY revenue DESC;


---Most Profitable Category

SELECT
    category,
    SUM(total_sale - cogs) AS total_profit
FROM retail_sales
GROUP BY category
ORDER BY total_profit DESC;


---Customer Retention Analysis

WITH customer_orders AS (
    SELECT
        customer_id,
        COUNT(transactions_id) AS total_orders
    FROM retail_sales
    GROUP BY customer_id
)
SELECT
    CASE
        WHEN total_orders = 1 THEN 'One-Time Customer'
        ELSE 'Returning Customer'
    END AS customer_type,
    COUNT(*) AS customer_count
FROM customer_orders
GROUP BY CASE
            WHEN total_orders = 1 THEN 'One-Time Customer'
            ELSE 'Returning Customer'
         END;


---Sales Performance by Age Group

SELECT
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        ELSE '46+'
    END AS age_group,
    SUM(total_sale) AS total_sales
FROM retail_sales
GROUP BY CASE
            WHEN age BETWEEN 18 AND 25 THEN '18-25'
            WHEN age BETWEEN 26 AND 35 THEN '26-35'
            WHEN age BETWEEN 36 AND 45 THEN '36-45'
            ELSE '46+'
         END
ORDER BY total_sales DESC;